name: CI

on:
  push:
    branches:
    - main
    - "**"
    tags:
  pull_request:
    branches:
    - main

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:

          - name: Python 3.10.xx with minimal dependencies 
            os: ubuntu-latest
            python: 3.10.16
            toxenv: py310-test

          - name: Python 3.10.xx with all optional dependencies 
            os: ubuntu-latest 
            python: 3.10.16
            toxenv: py310-test-alldeps 
            toxargs: -v --develop 
            toxposargs: -W error::ResourceWarning 

          - name: Python 3.11.xx with minimal dependencies 
            os: ubuntu-latest 
            python: 3.11.13 
            toxenv: py311-test 

          - name: Python 3.11.xx with all optional dependencies 
            os: ubuntu-latest 
            python: 3.11.13 
            toxenv: py311-test-alldeps 
            toxargs: -v --develop 
            toxposargs: -W error::ResourceWarning 

          - name: Python 3.12.xx with minimal dependencies 
            os: ubuntu-latest 
            python: 3.12.11
            toxenv: py312-test 

          - name: Python 3.12.xx with all optional dependencies 
            os: ubuntu-latest 
            python: 3.12.11
            toxenv: py312-test-alldeps 
            toxargs: -v --develop 
            toxposargs: -W error::ResourceWarning 

          - name: Python 3.13.xx with minimal dependencies 
            os: ubuntu-latest 
            python: 3.13.5
            toxenv: py313-test 

          - name: Python 3.13.xx with all optional dependencies 
            os: ubuntu-latest 
            python: 3.13.5
            toxenv: py313-test-alldeps 
            toxargs: -v --develop 
            toxposargs: -W error::ResourceWarning 

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov sphinx_rtd_theme
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00  # v5.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
